# Assignment:

## 1) Create a 3x3x3 array with random values.

In [1]:
import numpy as np
arr=np.random.random((3,3,3))
print("3x3x3 array with random values\n")
print(arr)

3x3x3 array with random values

[[[0.17665876 0.18557764 0.20296639]
  [0.35460528 0.10922152 0.35470997]
  [0.43603073 0.38995517 0.46018142]]

 [[0.14685062 0.96155628 0.10077823]
  [0.54663958 0.9487031  0.51862356]
  [0.89610859 0.3558192  0.71311391]]

 [[0.25942105 0.24913539 0.10785068]
  [0.58545305 0.62979111 0.22311353]
  [0.69955556 0.07819059 0.07211565]]]


 ## 2) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [2]:
matrix = np.zeros((5,5))
matrix = np.diag(np.arange(1,5),k=-1)
print('A 5x5 matrix with 1,2,3,4 just below Diagonal:\n\n', matrix)

A 5x5 matrix with 1,2,3,4 just below Diagonal:

 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


## 3) Create a 8x8 matrix and fill it with a checkerboard pattern.

In [3]:
matrix1=np.zeros((8,8),int)
matrix1[1::2,::2]=1
matrix1[::2,1::2]=1
print("Checkerboard pattern:\n")
print(matrix1)

Checkerboard pattern:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 4) Normalize a 5x5 random matrix. 

In [4]:
x=np.random.random((5,5))
print("Original:\n")
print(x)
xmax,xmin =x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("Normalization:\n")
print(x)

Original:

[[0.61119206 0.31836161 0.66314355 0.26822564 0.55560046]
 [0.97146221 0.69820121 0.71882921 0.86094104 0.86579487]
 [0.15215771 0.41821329 0.41746501 0.16559903 0.62752619]
 [0.58813049 0.78421047 0.26384824 0.23011091 0.14625205]
 [0.34626101 0.97641938 0.97914974 0.45345143 0.08869093]]
Normalization:

[[0.58677743 0.25792398 0.64511982 0.20162046 0.52434714]
 [0.99136678 0.68449015 0.70765573 0.86724967 0.87270061]
 [0.07127425 0.37005908 0.36921875 0.08636908 0.60512093]
 [0.56087891 0.78107997 0.19670457 0.15881698 0.06464209]
 [0.28925548 0.99693377 1.         0.40963209 0.        ]]


## 5)  How to find common values between two arrays?

In [5]:
array1 = np.array([0, 13, 25, 40, 68])
array2 = np.array([40, 13, 44,56,80])
print("Array1: ", array1)
print("Array2: ", array2)
print("Common values between two arrays:", np.intersect1d(array1, array2))

Array1:  [ 0 13 25 40 68]
Array2:  [40 13 44 56 80]
Common values between two arrays: [13 40]


## 6) How to get the dates of yesterday, today and tomorrow?

In [8]:
import datetime as dt
today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


## 7) Consider two random array A and B, check if they are equal.

In [9]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


## 8) Create random vector of size 10 and replace the maximum value by 0.

In [11]:
Z = np.random.random(10)
print("Intial one:\n",Z)
Z[Z.argmax()] = 0
print("After replacing the maximum value by 0:\n",Z)

Intial one:
 [0.75063006 0.41615779 0.68575199 0.70992623 0.63415883 0.04071509
 0.2588091  0.98097494 0.0726029  0.11209666]
After replacing the maximum value by 0:
 [0.75063006 0.41615779 0.68575199 0.70992623 0.63415883 0.04071509
 0.2588091  0.         0.0726029  0.11209666]


##  9) How to print all the values of an array?

In [12]:
print("1D array:\n")
a= np.array([1,2,32,3,4])
for i in range(len(a)):
    print(f"The element at index {i} is :{a[i]}")
print("2D array:\n")
b=np.array([[1,2,3],[5,6,7]])
for i in range(len(b)):
    print(f"The element at index {i} is : {b[i]}")

1D array:

The element at index 0 is :1
The element at index 1 is :2
The element at index 2 is :32
The element at index 3 is :3
The element at index 4 is :4
2D array:

The element at index 0 is : [1 2 3]
The element at index 1 is : [5 6 7]


## 10) Subtract the mean of each row of a matrix.

In [14]:
arr = np.array([[1,112,0,0], [2,165,0,0], [31,121,0,0]])
print('Initial Array:\n', arr)
print('Mean of Each row: ',arr.mean(axis=1))
mean = arr - arr.mean(axis=1, keepdims=True) 
print('\nResultant Matrix After Subtracting Mean:\n',mean)

Initial Array:
 [[  1 112   0   0]
 [  2 165   0   0]
 [ 31 121   0   0]]
Mean of Each row:  [28.25 41.75 38.  ]

Resultant Matrix After Subtracting Mean:
 [[-27.25  83.75 -28.25 -28.25]
 [-39.75 123.25 -41.75 -41.75]
 [ -7.    83.   -38.   -38.  ]]


## 11) Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [17]:
Z = np.ones(10)
print("Initial Vector:\n",Z)
I = np.random.randint(0, len(Z),20)
print("Random Values:\n",I)
Z += np.bincount(I, minlength=len(Z))
print("Resultant Vector:\n",Z)

Initial Vector:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Random Values:
 [1 9 6 8 5 1 6 3 6 2 8 2 7 1 7 4 9 6 9 2]
Resultant Vector:
 [1. 4. 4. 2. 2. 2. 5. 3. 3. 4.]


## 12) How to get the diagonal of a dot product?

In [21]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))

print("Array-1:\n",A)
print("Array-2:\n",B)

print('\nDot product:\n',np.dot(A,B))
print("The diagonal of a dot product:\n",np.diag(np.dot(A, B)))


Array-1:
 [[8 0 5]
 [6 3 8]
 [3 3 1]]
Array-2:
 [[5 7 5]
 [5 9 2]
 [9 3 9]]

Dot product:
 [[ 85  71  85]
 [117  93 108]
 [ 39  51  30]]
The diagonal of a dot product:
 [85 93 30]


## 13) How to find the most frequent value in an array?

In [25]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[8 9 2 6 7 5 4 2 3 7 8 9 3 7 9 2 7 9 4 6 0 5 7 7 6 4 0 0 4 6 4 7 2 9 6 8 2
 7 6 4 4 2 3 5 6 5 6 5 1 5]
rank: 6


## 14) How to get the n largest values of an array?

In [27]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


## 15) How to create a record array from a regular array?

In [32]:
Z = np.array([("Gayathri", 3.4, 8),
              ("Priya", 4.7, 9)])
print("Regular array:\n",Z)
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print("Record array:\n",R)

Regular array:
 [['Gayathri' '3.4' '8']
 ['Priya' '4.7' '9']]
Record array:
 [(b'Gayathri', 3.4, 8) (b'Priya', 4.7, 9)]
